// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	AccessTokenScopes = "accessToken.Scopes"
	TokenScopes       = "token.Scopes"
)

// Defines values for Role.
const (
	Admin   Role = "admin"
	Regular Role = "regular"
)

// File defines model for File.
type File struct {
	Location string    `json:"location"`
	Modified time.Time `json:"modified"`
	Name     string    `json:"name"`
	Size     int       `json:"size"`
	Type     string    `json:"type"`
}

// Folder defines model for Folder.
type Folder struct {
	ContentCount int       `json:"contentCount"`
	Location     string    `json:"location"`
	Modified     time.Time `json:"modified"`
	Name         string    `json:"name"`
	Size         int       `json:"size"`
}

// Role defines model for Role.
type Role string

// User defines model for User.
type User struct {
	Id       *string `json:"id,omitempty"`
	Role     *Role   `json:"role,omitempty"`
	Username *string `json:"username,omitempty"`
}

// LocationPath defines model for LocationPath.
type LocationPath = string

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// FolderContent defines model for FolderContent.
type FolderContent struct {
	Files   *[]File   `json:"files,omitempty"`
	Folders *[]Folder `json:"folders,omitempty"`
}

// GetFIleResponse defines model for GetFIleResponse.
type GetFIleResponse struct {
	Content *string `json:"content,omitempty"`
	Info    File    `json:"info"`
}

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	Success *string `json:"success,omitempty"`
}

// NewFileRequest defines model for NewFileRequest.
type NewFileRequest struct {
	IsDir bool   `json:"isDir"`
	Name  string `json:"name"`
}

// GetBlobParams defines parameters for GetBlob.
type GetBlobParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// PostBlobMultipartBody defines parameters for PostBlob.
type PostBlobMultipartBody struct {
	Files [][]byte `json:"files"`
}

// PostBlobParams defines parameters for PostBlob.
type PostBlobParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// PostCopyJSONBody defines parameters for PostCopy.
type PostCopyJSONBody struct {
	Destination string   `json:"destination"`
	Sources     []string `json:"sources"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// PatchFileJSONBody defines parameters for PatchFile.
type PatchFileJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// PatchFileParams defines parameters for PatchFile.
type PatchFileParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// PostFileJSONBody defines parameters for PostFile.
type PostFileJSONBody struct {
	IsDir bool   `json:"isDir"`
	Name  string `json:"name"`
}

// PostFileParams defines parameters for PostFile.
type PostFileParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// GetFolderParams defines parameters for GetFolder.
type GetFolderParams struct {
	Path LocationPath `form:"path" json:"path"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostMoveJSONBody defines parameters for PostMove.
type PostMoveJSONBody struct {
	Destination string   `json:"destination"`
	Sources     []string `json:"sources"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	Path        string `form:"path" json:"path"`
	SearchQuery string `form:"searchQuery" json:"searchQuery"`
}

// PatchUserIdJSONBody defines parameters for PatchUserId.
type PatchUserIdJSONBody struct {
	Password *string `json:"password,omitempty"`
	Role     *Role   `json:"role,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostUserIdJSONBody defines parameters for PostUserId.
type PostUserIdJSONBody struct {
	Password string `json:"password"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// PostBlobMultipartRequestBody defines body for PostBlob for multipart/form-data ContentType.
type PostBlobMultipartRequestBody PostBlobMultipartBody

// PostCopyJSONRequestBody defines body for PostCopy for application/json ContentType.
type PostCopyJSONRequestBody PostCopyJSONBody

// PatchFileJSONRequestBody defines body for PatchFile for application/json ContentType.
type PatchFileJSONRequestBody PatchFileJSONBody

// PostFileJSONRequestBody defines body for PostFile for application/json ContentType.
type PostFileJSONRequestBody PostFileJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostMoveJSONRequestBody defines body for PostMove for application/json ContentType.
type PostMoveJSONRequestBody PostMoveJSONBody

// PatchUserIdJSONRequestBody defines body for PatchUserId for application/json ContentType.
type PatchUserIdJSONRequestBody PatchUserIdJSONBody

// PostUserIdJSONRequestBody defines body for PostUserId for application/json ContentType.
type PostUserIdJSONRequestBody PostUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Your GET endpoint
	// (GET /access-token)
	GetAccessToken(ctx echo.Context) error
	// Your GET endpoint
	// (GET /blob)
	GetBlob(ctx echo.Context, params GetBlobParams) error

	// (POST /blob)
	PostBlob(ctx echo.Context, params PostBlobParams) error

	// (POST /copy)
	PostCopy(ctx echo.Context) error

	// (DELETE /file)
	DeleteFile(ctx echo.Context, params DeleteFileParams) error
	// Your GET endpoint
	// (GET /file)
	GetFile(ctx echo.Context, params GetFileParams) error

	// (PATCH /file)
	PatchFile(ctx echo.Context, params PatchFileParams) error

	// (POST /file)
	PostFile(ctx echo.Context, params PostFileParams) error
	// Your GET endpoint
	// (GET /folder)
	GetFolder(ctx echo.Context, params GetFolderParams) error

	// (POST /login)
	PostLogin(ctx echo.Context) error

	// (POST /move)
	PostMove(ctx echo.Context) error
	// Your GET endpoint
	// (GET /search)
	GetSearch(ctx echo.Context, params GetSearchParams) error

	// (DELETE /user/{id})
	DeleteUserId(ctx echo.Context, id string) error
	// Your GET endpoint
	// (GET /user/{id})
	GetUser(ctx echo.Context, id string) error

	// (PATCH /user/{id})
	PatchUserId(ctx echo.Context, id string) error

	// (POST /user/{id})
	PostUserId(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAccessToken converts echo context to params.
func (w *ServerInterfaceWrapper) GetAccessToken(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAccessToken(ctx)
	return err
}

// GetBlob converts echo context to params.
func (w *ServerInterfaceWrapper) GetBlob(ctx echo.Context) error {
	var err error

	ctx.Set(AccessTokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBlobParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBlob(ctx, params)
	return err
}

// PostBlob converts echo context to params.
func (w *ServerInterfaceWrapper) PostBlob(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostBlobParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostBlob(ctx, params)
	return err
}

// PostCopy converts echo context to params.
func (w *ServerInterfaceWrapper) PostCopy(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostCopy(ctx)
	return err
}

// DeleteFile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteFile(ctx, params)
	return err
}

// GetFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFile(ctx, params)
	return err
}

// PatchFile converts echo context to params.
func (w *ServerInterfaceWrapper) PatchFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchFile(ctx, params)
	return err
}

// PostFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFile(ctx, params)
	return err
}

// GetFolder converts echo context to params.
func (w *ServerInterfaceWrapper) GetFolder(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFolderParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFolder(ctx, params)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostMove converts echo context to params.
func (w *ServerInterfaceWrapper) PostMove(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMove(ctx)
	return err
}

// GetSearch converts echo context to params.
func (w *ServerInterfaceWrapper) GetSearch(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Required query parameter "searchQuery" -------------

	err = runtime.BindQueryParameter("form", true, true, "searchQuery", ctx.QueryParams(), &params.SearchQuery)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter searchQuery: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSearch(ctx, params)
	return err
}

// DeleteUserId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUserId(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// PatchUserId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchUserId(ctx, id)
	return err
}

// PostUserId converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/access-token", wrapper.GetAccessToken)
	router.GET(baseURL+"/blob", wrapper.GetBlob)
	router.POST(baseURL+"/blob", wrapper.PostBlob)
	router.POST(baseURL+"/copy", wrapper.PostCopy)
	router.DELETE(baseURL+"/file", wrapper.DeleteFile)
	router.GET(baseURL+"/file", wrapper.GetFile)
	router.PATCH(baseURL+"/file", wrapper.PatchFile)
	router.POST(baseURL+"/file", wrapper.PostFile)
	router.GET(baseURL+"/folder", wrapper.GetFolder)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/move", wrapper.PostMove)
	router.GET(baseURL+"/search", wrapper.GetSearch)
	router.DELETE(baseURL+"/user/:id", wrapper.DeleteUserId)
	router.GET(baseURL+"/user/:id", wrapper.GetUser)
	router.PATCH(baseURL+"/user/:id", wrapper.PatchUserId)
	router.POST(baseURL+"/user/:id", wrapper.PostUserId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW1PjNhT+Kxp1n1qDE9id2fFT90qZ3e1eWB46QGeEfZxokSUjyQmByX/v6OJLEiUk",
	"AbaF6ROxLJ3b9+mcI5kbnIqiFBy4Vji5wSWRpAAN0j59FCnRVPAvRA/NM+U4wZcVyAmOMCcF4ASX5l2E",
	"JVxWVEKGEy0riLBKh1AQs0hPSjNPaUn5AE+nUzcZlH4tMgpW0Z8wfk8ZfHPjZiQVXAO3P0lZMuoMiX8o",
	"wc1YK76UogSpvSCq3lLZ0XouBAPC8bS2d9Geru0nblbk5ZxF9Wxx/gNSbax3C1QpuHIq30kp5BomwxUp",
	"SubXuN+obx5GhFXWMnCSatMiXIBSZDAfvWW+Q23InIcdOSHvFzyMcAYqlbQ05uMEGwnvBctAvmk93BKf",
	"nPoIUA2F/fFMQo4T/EvcEjF2q1VsOIFbE4mUZGKec2vNBnLs/EVJ63p/APr9oaGng/0O/neWLaBEeS7W",
	"i8gcZ+3CszV8qWlX89doParSFJT61FLkzjxWTiROsDEXSTCbKkN+OK8Ym6xmciNgS742oq0IG7MFHczn",
	"tvCGERnNqYnuDc6FLIjGCc6Ihh1NbX5YWLEku0RY0Wv7oqCcFlWBk16zmnINgy4vm+DiBGu40nHJCOU4",
	"MklWgzTO/X16Ov7t9DQ2f54tGhLOZnZS1Lrsrer4adhDtVVswzUf5ghf7SgtSkYHQ8sMmuEEV7398fX1",
	"y2KkSa+yyv1OW8b7N6JyxFodjf8SNuGIdkLZ2NNEdcbZbmRdcNaL7T4DxvsXRbF3cUGtGd+E4zFwY+oJ",
	"JllhySFhUDEiu5rs1PlIhPVcTS4L2d/n4sXeeWr1HKsQgjQLhlB6o1YlLWvNNMKVArm8Cte2W/Xrxeh5",
	"/oMz2R9cvaAXlz6lQFpJqidHRreznNhk8l1cAF/WxHSntEWipB/A1htdr7Ue2b4CiOyaOdS6dAbUWdyQ",
	"gKTWVigIZTiph36/FJLuZjBq9X8VkqJ3bOcPktNr005VknmpKonj8Xi82yxayHc2yR5VMgeJXn05xLNb",
	"efbNCKRyq/q7PSNKlMBJSQ3hds2QzTVDG7fYRWWn8X4A1p1Z7a/UBcqFRHYW0gK5VchUepSJMWeCZAh0",
	"iq0yabfNoUHvAPSrmbjPtFV7vd4d6uwc5ltUkc8fTHie9/aXsbuxNnYdYJd9ODm5qVlzcjY9i7CqioLI",
	"CU7wX6KS6ODddwQ8KwXlhtyaDJTd0pUe4jMjKT5n4nxp0N/WcbVRJhoN6Ag48r34QphfG1nRTHN/Enaq",
	"nRLPNP/GhTvB02Tqc8qJ3XqBc0EYgd7aCGyGl5n9fGt0Zxi2CcYW2LNphEuhAtAelxZY4qDVArlmF2WQ",
	"Uw4Zoktg/iLUveFcn84mcxAXFdO0JFLHBs6djGhyG8q3tf/tiokOFu+Fjr1bjZ284DFtga/926Ge64Uf",
	"lH0rs8UcV0w+SEVp4Qiz5o0oJ4hRpZHILXMUIjzz3FFd8ihRyRSUYVYGSlNuwfczg6wysvEqWmySmDs6",
	"wy2ZM2+GI5txopYQzehajyOb5bS1asi0RTNltDwXRGYe0twfTDJgoCGQ5e24hXMBGPfO9+oPkNgf2Uax",
	"MTJJNVguJehKct+TmAZtF9EcGfgQVcietH5FVKMxZQzVk6lGngmIqOanZ/MkVGb/LTTmrye2gKP/k6rm",
	"Fj1RA21JdDoMgWuaaIetP53N5TCz7r6wuY8cuOIMtGaKeqy7M1y8UglEA+IwRlCUehLOeKYUPQiKYT87",
	"N9Tx3PX0kwLFFqLm1iaYPj+XwE1D6hpR01fUOXJ5x0G5ohkEs2Tdafz0PDl7if3EsqSLqsOTiQHly5vF",
	"j/Z1aH/Vb+4nz5VEqbGQmb9i+wh8oIc46Qe6/O7V0Mqpc81esy5qtT1EqzfrmF5+r9A1zk072+CyoX8H",
	"ozofeTLIScW0vcYcEUYzVMcJCYmaQEXb3Iscc1LpoZD0GrKZ7rZzd1GIESyn3ycxgoc6qxjZ/59VHuCs",
	"ooBI130FS8SRfe2aMCHrUmEgTEUJ2TLIDkC7lYvl4F6+NUdhOc6Zr35wfXE/v+rcQ2XwyDkYTR6Ib2g2",
	"XXXudOM2Zyw5dx4rkIcZfhJ9kHVz6dHxALQNhD02hvjrP1fcaXOu+nhi5T+629EteNrgEEoEfuf7/Uuz",
	"Tbft6rOjkCgdEj6Abm0MHCI7tL/v/ughP6w9zUNly5fbDpXBRGa6hceJ5239r9f1dG/FPfJushzViaL9",
	"ZprEMRMpYUOhdLLf6/VwZ/lN89HXNKymRfDP9rK989y2QJ3B3P1LUvtc/2vRzWxz0R2x9hoLQt+wX+pr",
	"cSGvRnt7aW+Mp9N/AgAA//9/2D4ZkicAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
