// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	AccessTokenScopes = "accessToken.Scopes"
	TokenScopes       = "token.Scopes"
)

// Defines values for Role.
const (
	Admin   Role = "admin"
	Regular Role = "regular"
)

// File defines model for File.
type File struct {
	Location string    `json:"location"`
	Modified time.Time `json:"modified"`
	Name     string    `json:"name"`
	Size     int       `json:"size"`
	Type     string    `json:"type"`
}

// Folder defines model for Folder.
type Folder struct {
	ContentCount int       `json:"contentCount"`
	Location     string    `json:"location"`
	Modified     time.Time `json:"modified"`
	Name         string    `json:"name"`
	Size         int       `json:"size"`
}

// Role defines model for Role.
type Role string

// User defines model for User.
type User struct {
	Id       string `json:"id"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// PathParam defines model for PathParam.
type PathParam = string

// Error defines model for Error.
type Error struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// FolderContent defines model for FolderContent.
type FolderContent struct {
	Files   []File   `json:"files"`
	Folders []Folder `json:"folders"`
}

// GetFIleResponse defines model for GetFIleResponse.
type GetFIleResponse struct {
	Content *string `json:"content,omitempty"`
	Info    File    `json:"info"`
}

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	Success string `json:"success"`
}

// NewFileRequest defines model for NewFileRequest.
type NewFileRequest struct {
	IsDir bool   `json:"isDir"`
	Name  string `json:"name"`
}

// PasteRequest defines model for PasteRequest.
type PasteRequest struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// GetBlobParams defines parameters for GetBlob.
type GetBlobParams struct {
	Path PathParam `form:"path" json:"path"`
}

// PostBlobMultipartBody defines parameters for PostBlob.
type PostBlobMultipartBody struct {
	Files [][]byte `json:"files"`
}

// PostBlobParams defines parameters for PostBlob.
type PostBlobParams struct {
	Path PathParam `form:"path" json:"path"`
}

// PostCopyJSONBody defines parameters for PostCopy.
type PostCopyJSONBody struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	Paths []string `form:"paths" json:"paths"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	Path PathParam `form:"path" json:"path"`
}

// PatchFileJSONBody defines parameters for PatchFile.
type PatchFileJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// PatchFileParams defines parameters for PatchFile.
type PatchFileParams struct {
	Path PathParam `form:"path" json:"path"`
}

// PostFileJSONBody defines parameters for PostFile.
type PostFileJSONBody struct {
	IsDir bool   `json:"isDir"`
	Name  string `json:"name"`
}

// PostFileParams defines parameters for PostFile.
type PostFileParams struct {
	Path PathParam `form:"path" json:"path"`
}

// GetFolderParams defines parameters for GetFolder.
type GetFolderParams struct {
	Path PathParam `form:"path" json:"path"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostMoveJSONBody defines parameters for PostMove.
type PostMoveJSONBody struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	Path        string `form:"path" json:"path"`
	SearchQuery string `form:"searchQuery" json:"searchQuery"`
}

// PatchUserIdJSONBody defines parameters for PatchUserId.
type PatchUserIdJSONBody struct {
	Password *string `json:"password,omitempty"`
	Role     *Role   `json:"role,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostUserIdJSONBody defines parameters for PostUserId.
type PostUserIdJSONBody struct {
	Password string `json:"password"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// PostBlobMultipartRequestBody defines body for PostBlob for multipart/form-data ContentType.
type PostBlobMultipartRequestBody PostBlobMultipartBody

// PostCopyJSONRequestBody defines body for PostCopy for application/json ContentType.
type PostCopyJSONRequestBody PostCopyJSONBody

// PatchFileJSONRequestBody defines body for PatchFile for application/json ContentType.
type PatchFileJSONRequestBody PatchFileJSONBody

// PostFileJSONRequestBody defines body for PostFile for application/json ContentType.
type PostFileJSONRequestBody PostFileJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostMoveJSONRequestBody defines body for PostMove for application/json ContentType.
type PostMoveJSONRequestBody PostMoveJSONBody

// PatchUserIdJSONRequestBody defines body for PatchUserId for application/json ContentType.
type PatchUserIdJSONRequestBody PatchUserIdJSONBody

// PostUserIdJSONRequestBody defines body for PostUserId for application/json ContentType.
type PostUserIdJSONRequestBody PostUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Your GET endpoint
	// (GET /access-token)
	GetAccessToken(ctx echo.Context) error
	// Your GET endpoint
	// (GET /blob)
	GetBlob(ctx echo.Context, params GetBlobParams) error

	// (POST /blob)
	PostBlob(ctx echo.Context, params PostBlobParams) error

	// (POST /copy)
	PostCopy(ctx echo.Context) error

	// (DELETE /file)
	DeleteFile(ctx echo.Context, params DeleteFileParams) error
	// Your GET endpoint
	// (GET /file)
	GetFile(ctx echo.Context, params GetFileParams) error

	// (PATCH /file)
	PatchFile(ctx echo.Context, params PatchFileParams) error

	// (POST /file)
	PostFile(ctx echo.Context, params PostFileParams) error
	// Your GET endpoint
	// (GET /folder)
	GetFolder(ctx echo.Context, params GetFolderParams) error

	// (POST /login)
	PostLogin(ctx echo.Context) error

	// (POST /move)
	PostMove(ctx echo.Context) error
	// Your GET endpoint
	// (GET /search)
	GetSearch(ctx echo.Context, params GetSearchParams) error

	// (DELETE /user/{id})
	DeleteUserId(ctx echo.Context, id string) error
	// Your GET endpoint
	// (GET /user/{id})
	GetUser(ctx echo.Context, id string) error

	// (PATCH /user/{id})
	PatchUserId(ctx echo.Context, id string) error

	// (POST /user/{id})
	PostUserId(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAccessToken converts echo context to params.
func (w *ServerInterfaceWrapper) GetAccessToken(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAccessToken(ctx)
	return err
}

// GetBlob converts echo context to params.
func (w *ServerInterfaceWrapper) GetBlob(ctx echo.Context) error {
	var err error

	ctx.Set(AccessTokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBlobParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBlob(ctx, params)
	return err
}

// PostBlob converts echo context to params.
func (w *ServerInterfaceWrapper) PostBlob(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostBlobParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostBlob(ctx, params)
	return err
}

// PostCopy converts echo context to params.
func (w *ServerInterfaceWrapper) PostCopy(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostCopy(ctx)
	return err
}

// DeleteFile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFileParams
	// ------------- Required query parameter "paths" -------------

	err = runtime.BindQueryParameter("form", true, true, "paths", ctx.QueryParams(), &params.Paths)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter paths: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteFile(ctx, params)
	return err
}

// GetFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFile(ctx, params)
	return err
}

// PatchFile converts echo context to params.
func (w *ServerInterfaceWrapper) PatchFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchFile(ctx, params)
	return err
}

// PostFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostFile(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFileParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFile(ctx, params)
	return err
}

// GetFolder converts echo context to params.
func (w *ServerInterfaceWrapper) GetFolder(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFolderParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFolder(ctx, params)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostMove converts echo context to params.
func (w *ServerInterfaceWrapper) PostMove(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMove(ctx)
	return err
}

// GetSearch converts echo context to params.
func (w *ServerInterfaceWrapper) GetSearch(ctx echo.Context) error {
	var err error

	ctx.Set(TokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Required query parameter "searchQuery" -------------

	err = runtime.BindQueryParameter("form", true, true, "searchQuery", ctx.QueryParams(), &params.SearchQuery)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter searchQuery: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSearch(ctx, params)
	return err
}

// DeleteUserId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUserId(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// PatchUserId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchUserId(ctx, id)
	return err
}

// PostUserId converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(TokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/access-token", wrapper.GetAccessToken)
	router.GET(baseURL+"/blob", wrapper.GetBlob)
	router.POST(baseURL+"/blob", wrapper.PostBlob)
	router.POST(baseURL+"/copy", wrapper.PostCopy)
	router.DELETE(baseURL+"/file", wrapper.DeleteFile)
	router.GET(baseURL+"/file", wrapper.GetFile)
	router.PATCH(baseURL+"/file", wrapper.PatchFile)
	router.POST(baseURL+"/file", wrapper.PostFile)
	router.GET(baseURL+"/folder", wrapper.GetFolder)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/move", wrapper.PostMove)
	router.GET(baseURL+"/search", wrapper.GetSearch)
	router.DELETE(baseURL+"/user/:id", wrapper.DeleteUserId)
	router.GET(baseURL+"/user/:id", wrapper.GetUser)
	router.PATCH(baseURL+"/user/:id", wrapper.PatchUserId)
	router.POST(baseURL+"/user/:id", wrapper.PostUserId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xaW3PbuBX+Kxh0n1ralOzszA6fms0mrmd3u04cP3RsdQYmDyXEIEADoGTZo//ewYUX",
	"SaAutpImfrIIAgfnfN/BuYB+wqkoSsGBa4WTJ1wSSQrQIO3TBdGTCzNiHijHCb6vQM5xhDkpACe4JHqC",
	"IyzhvqISMpxoWUGEVTqBgphFel6aeUpLysd4sVi4yaD0ryKjYHf5N8w+UAaf3LgZSQXXwO1PUpaMpkRT",
	"weMvSnAz1oovpShBai+Iqt+o7Ox6KwQDwvGi1nddn67u125W5OWMonq2uP0CqTbaLyJ8QZQ+gK4ZKE25",
	"nRvQK8JKVDL1ZmkoVHCSHyBSkrk1Zl1ha6EqBVdO2HsphdxBb3ggRcn8GvcbDc3DlLDKQglOUq1OhAtQ",
	"ioxX6e4DAGpF1qxq5Gyjy4loF4QYiwzSqaSlQxqbDT4IloF81wLwTA5zylYY+klCjhP8t7g9VbFbrWLj",
	"4+ukRTi32uwhx84P0t8FxynXit8VnDPQH87NaXRO8wJ4OsvWOKY8F7sBtmKWXbiLLbXT1t5vdr2s0hSU",
	"+rN1sBefAuVE4gQbdZEEE0My5IfzirH55nPQCNjm7fXE3YhsdrSSLZRrWzOR9gegQmQ0p2brJ5wLWRCN",
	"E5wRDUea2ii5tqInxkZY0Uf7oqCcFlWBk0GzmnIN4643N5jjBGt40HHJCOU4MqlGgzTG/ffmZvaPm5vY",
	"/PlpXZFwTLeTotZkr1XHToMr1XZjC9cqzBF+OFJalIyOJ9ZhaIYTXA1OZ4+PvxRTTQaV3dyfz77j8E5U",
	"zt82o/E9cRNGtANlo0+D6pKxXWQdOLthe8qA8eFdUZzc3VGrxifh/Bi4UfUak6ywziFhXDEiuzvZqatI",
	"hPd5mN8XcnjKxc8nt6nd50qFGKRZEELpldoUy6w2iwhXCuRutQg1aDbT/S4d+6yKu+H4Jv/CmRyOH36m",
	"d/c+GkFaSarnl0Y/Zx2x4eWzuAPeV+51p7Tpp6S/g81kul5rrbYVGBDZVXOidekUqBOAcRSSWl2hIJTh",
	"pB76572Q9DiDabv/RyEpes+O/kVy+mgKz0oyL1UlcTybzY6bRWsx0cbny0rmINHbi3O8fNyX30xBKrdq",
	"eDwwokQJnJTUOOWxGbLxaGJxix0qR431Y9C+wuvs/lbdoVxIZGchLZBbhUyaRpmYcSZIhkCn2G4m7dE6",
	"N+ydgX67hPtSPXcyGLwgRa9wvu6RWzPNX78beN4MTvtOQKNt7ErPrvfh5Pqp9prr0WIUYVUVBZFznOD/",
	"iEqis/efEfCsFJQb59ZkrOyxr/QEj4yk+JaJ217Qf6txtSgTjcZ0Chz5rmUN5l+NrGipB7oOG9VOidse",
	"yej/Im6aUH5LObHnLtA+heEf7Az/fmSZ2W+eTe2Se+1DsGV1tIhwKVSA16vSskocr1ogV+SiDHLKIUO0",
	"h+MLoQ5Dct3Bzlf4LSqmaUmkjg2XRxnRZBvF21qKdsVcB1P7Dl1ATyu74qzD7TyvFNBf1fU2xokVRzGR",
	"IBWlpSPsMu9EOUeMKo1Ebt1GIcIz7ziq6zm+8zZu1WnS/cygSxnZeM0twkZ27j7ipauERTh47MfHokUm",
	"ZbS8FURmHp7ctwAZMNAQiJV23EKzZqR756vilZPTdy2kNt4L9d9pFJSfu5fDNd8eHQKj/7vPWohNcAvm",
	"LAm6ktwXBqZKOkY0RwYIRBWyLdHfEdVoRhlD9WSqkY9CiKjmpw8t81CuC5P54ly3GaXVu4VncDH8Rqnr",
	"GVVJw2tJdDoJMWuOhyPWF/UrscSsOwgxfflpn9qwv03ZIZf80OcynEFSCUQD4jBDUJR6Hg6VJh8cnsLt",
	"uWTlEv1VMWLTV3OrEoyaf5XATT3o6kCT2evQ2J/zKVc0g2BwrHP9tw2Py/fSryw4OkgdmUyMKe+v1f6w",
	"r0Mnq35zmAhXEqVmQmb+/usP4GM96dYdbVXSvbfZOHWl/u5c4DS7jXaPoM80TPc39F3l3LTRHl3+8AVK",
	"dT7rZJCTiml7xzgljGaoxgkJiRqgoudcSFxxUumJkPQRsqWCuHNpUIgp9Lvfn2IKX6tVMLK/+1ZBAZGu",
	"gAnG2kv72tUxQtYx18CRihKyPvPPQLuVu/cQe31ajsJynDEf/eDu4r59BD9AlPXMORrNmYqfaLbY1Pa5",
	"cXv+etq+KwXyPMOvoqCwZva2XmegLRC27Qr5r79zf1Gk3vSVwMr/4W75nuGnDQ+hQOBPvj+/NNv32G5u",
	"v4RE6YTwMXTzTKAP67j9oWuNr/gF6ZW2Zq2/bGvNgoHMZN4fk89ttWTnu+DrvOD1zLvJcloHivbDXxLH",
	"TKSETYTSyelgMMCd5U/Nl0tT/JkSwT/be+POc1sCdQZz9x877XP9nzdPy8VFd8TqazQIfYj9RT+KO/kw",
	"PTlJBzO8WPwvAAD//089mGt+JwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
