// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"time"
)

const (
	AccessTokenScopes = "accessToken.Scopes"
	TokenScopes       = "token.Scopes"
)

// File defines model for File.
type File struct {
	Location string    `json:"location"`
	Modified time.Time `json:"modified"`
	Name     string    `json:"name"`
	Size     int       `json:"size"`
	Type     string    `json:"type"`
	Url      string    `json:"url"`
}

// Folder defines model for Folder.
type Folder struct {
	ContentCount int       `json:"contentCount"`
	Location     string    `json:"location"`
	Modified     time.Time `json:"modified"`
	Name         string    `json:"name"`
	Url          string    `json:"url"`
}

// FolderContent defines model for FolderContent.
type FolderContent struct {
	Files   []File   `json:"files"`
	Folders []Folder `json:"folders"`
}

// PasteRequest defines model for PasteRequest.
type PasteRequest struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// PostCopyJSONBody defines parameters for PostCopy.
type PostCopyJSONBody struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// PatchFileJSONBody defines parameters for PatchFile.
type PatchFileJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// PostFileJSONBody defines parameters for PostFile.
type PostFileJSONBody struct {
	IsDir bool   `json:"isDir"`
	Name  string `json:"name"`
}

// PostBlobMultipartBody defines parameters for PostBlob.
type PostBlobMultipartBody struct {
	Files [][]byte `json:"files"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostMoveJSONBody defines parameters for PostMove.
type PostMoveJSONBody struct {
	Destination *string   `json:"destination,omitempty"`
	Sources     *[]string `json:"sources,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	Path        string `form:"path" json:"path"`
	SearchQuery string `form:"searchQuery" json:"searchQuery"`
}

// PostCopyJSONRequestBody defines body for PostCopy for application/json ContentType.
type PostCopyJSONRequestBody PostCopyJSONBody

// PatchFileJSONRequestBody defines body for PatchFile for application/json ContentType.
type PatchFileJSONRequestBody PatchFileJSONBody

// PostFileJSONRequestBody defines body for PostFile for application/json ContentType.
type PostFileJSONRequestBody PostFileJSONBody

// PostBlobMultipartRequestBody defines body for PostBlob for multipart/form-data ContentType.
type PostBlobMultipartRequestBody PostBlobMultipartBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostMoveJSONRequestBody defines body for PostMove for application/json ContentType.
type PostMoveJSONRequestBody PostMoveJSONBody
