### create new empty file named empty-file
POST http://localhost:3000/file/empty-file

### open empty file
GET  http://localhost:3000/file/empty-file

### create new empty file again
POST http://localhost:3000/file/empty-file

### rename empty-file to new-file
PATCH  http://localhost:3000/file/empty-file
content-type: application/json

{
  "name": "new-file"
}

### Delete new-file
DELETE http://localhost:3000/file/new-file

###
GET http://localhost:3000/file/cat.jpg/blob